name: Cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run cppcheck
      run: cppcheck-2.5 3_Implementation